# Generated by Django 5.2.3 on 2025-08-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='service_provider',
            new_name='service_provider_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('basic_service', 'Basic Service'), ('standard_service', 'Standard Service'), ('full_service', 'Full Service')], default='basic_service', max_length=100),
        ),
        migrations.CreateModel(
            name='Previous_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(upload_to='previous_work_images/')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.providerprofilemodel')),
            ],
        ),
    ]
