# Generated by Django 5.2.3 on 2025-08-11 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_customer_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previous_work',
            old_name='description',
            new_name='service_description',
        ),
        migrations.RenameField(
            model_name='previous_work',
            old_name='service_name',
            new_name='service_title',
        ),
        migrations.AlterField(
            model_name='previous_work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
