# Generated by Django 5.2.3 on 2025-08-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_description_previous_work_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.providerprofilemodel'),
        ),
    ]
