# Generated by Django 5.2.3 on 2025-08-11 10:51

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_previous_work_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_work',
            name='service_image',
            field=models.ImageField(upload_to=myapp.models.previous_work_image),
        ),
    ]
