# Generated by Django 5.2.3 on 2025-08-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_previous_work_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofilemodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
