# Generated by Django 5.2.3 on 2025-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_providerprofilemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofilemodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
