# Generated by Django 5.2.3 on 2025-08-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_providerprofilemodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofilemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
