# Generated by Django 5.2.3 on 2025-08-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_providerprofilemodel_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
