# Generated by Django 5.2.3 on 2025-08-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('full_address', models.TextField()),
                ('service_type', models.CharField(choices=[('basic_service', 'Basic Service'), ('standard_service', 'Standard Service'), ('full_service', 'Full Service')], default='basic_service', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customerprofilemodel')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.providerprofilemodel')),
            ],
        ),
    ]
