# Generated by Django 5.2.3 on 2025-08-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
    ]
