# Generated by Django 5.2.3 on 2025-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('accept', 'Accept'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
