# Generated by Django 5.2.3 on 2025-08-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_bookingreviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingreviews',
            old_name='comment',
            new_name='review_text',
        ),
    ]
