# Generated by Django 5.2.3 on 2025-08-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_comment_bookingreviews_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingreviews',
            old_name='booking_reviews',
            new_name='booking_review',
        ),
    ]
