# Generated by Django 5.2.3 on 2025-08-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_booking_reviews_bookingreviews_booking_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingReviews',
        ),
    ]
