# Generated by Django 5.2.3 on 2025-08-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_bookingreviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingReviews',
        ),
    ]
