# Generated by Django 5.2.3 on 2025-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_bookingreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreviews',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
