# Generated by Django 5.2.3 on 2025-08-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_bookingreviews_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingreviews',
            old_name='provider',
            new_name='service_provider',
        ),
    ]
