# Generated by Django 5.2.3 on 2025-08-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_provider_bookingreviews_service_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previous_work',
            old_name='user',
            new_name='service_provider',
        ),
    ]
