# Generated by Django 5.2.3 on 2025-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_user_previous_work_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofilemodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
