# Generated by Django 5.2.3 on 2025-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_providerprofilemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='providerprofilemodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
