# Generated by Django 5.2.3 on 2025-08-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_bookingreviews_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofilemodel',
            name='rating',
        ),
    ]
