# Generated by Django 5.2.3 on 2025-08-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_providerprofilemodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('service_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='average_rating', to='myapp.providerprofilemodel')),
            ],
        ),
    ]
