# Generated by Django 5.2.3 on 2025-08-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_averagerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreviews',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
