# Generated by Django 5.2.3 on 2025-09-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_user',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
